import { DistrictData, GisMapPin, IpQueueItem, CivicProject, IpRegistryItem, ReportConfig } from "./types";

export const JHARKHAND_DISTRICTS: DistrictData[] = [
  {
    id: "ranchi",
    name: "Ranchi",
    division: "South Chotanagpur",
    center: [380, 310],
    path: "M 330,270 L 410,270 L 430,330 L 390,360 L 330,340 Z",
    nodalOfficer: {
      name: "Er. Rajesh K. Tiwari",
      designation: "District Nodal Officer (Technical)",
      email: "dno.ranchi@jharkhand.gov.in",
      phone: "+91-94311-20411",
      dscVerified: true,
    },
    activeBuilds: 34,
    csrDeployedCr: 1.2,
    civicBacklogCount: 14,
    complaintsLogged: 342,
    complaintsResolved: 312,
    resolutionSpeedHours: 3.2,
    triageMunicipalPercent: 62,
    triageAcademicPercent: 38,
    departments: { water: 12, roads: 8, energy: 9, urban: 5 },
  },
  {
    id: "dhanbad",
    name: "Dhanbad",
    division: "North Chotanagpur",
    center: [520, 240],
    path: "M 480,210 L 560,210 L 570,260 L 510,280 L 480,250 Z",
    nodalOfficer: {
      name: "Dr. Alok Verma",
      designation: "District Nodal Officer (Mining & Industry)",
      email: "dno.dhanbad@jharkhand.gov.in",
      phone: "+91-94311-88421",
      dscVerified: true,
    },
    activeBuilds: 28,
    csrDeployedCr: 0.95,
    civicBacklogCount: 18,
    complaintsLogged: 410,
    complaintsResolved: 375,
    resolutionSpeedHours: 3.8,
    triageMunicipalPercent: 58,
    triageAcademicPercent: 42,
    departments: { water: 10, roads: 6, energy: 8, urban: 4 },
  },
  {
    id: "east_singhbhum",
    name: "East Singhbhum",
    division: "Kolhan",
    center: [560, 430],
    path: "M 520,380 L 610,390 L 620,460 L 540,470 L 510,430 Z",
    nodalOfficer: {
      name: "Smt. Priyanka Soren",
      designation: "District Nodal Officer (Urban Infrastructure)",
      email: "dno.esinghbhum@jharkhand.gov.in",
      phone: "+91-94311-55102",
      dscVerified: true,
    },
    activeBuilds: 26,
    csrDeployedCr: 0.88,
    civicBacklogCount: 12,
    complaintsLogged: 380,
    complaintsResolved: 350,
    resolutionSpeedHours: 3.5,
    triageMunicipalPercent: 65,
    triageAcademicPercent: 35,
    departments: { water: 8, roads: 7, energy: 6, urban: 5 },
  },
  {
    id: "bokaro",
    name: "Bokaro",
    division: "North Chotanagpur",
    center: [450, 260],
    path: "M 410,240 L 480,230 L 490,290 L 430,300 L 400,260 Z",
    nodalOfficer: {
      name: "Er. Sanjeev Murmu",
      designation: "District Nodal Officer",
      email: "dno.bokaro@jharkhand.gov.in",
      phone: "+91-94311-77312",
      dscVerified: true,
    },
    activeBuilds: 18,
    csrDeployedCr: 0.42,
    civicBacklogCount: 9,
    complaintsLogged: 290,
    complaintsResolved: 265,
    resolutionSpeedHours: 4.1,
    triageMunicipalPercent: 70,
    triageAcademicPercent: 30,
    departments: { water: 5, roads: 6, energy: 4, urban: 3 },
  },
  {
    id: "hazaribagh",
    name: "Hazaribagh",
    division: "North Chotanagpur",
    center: [360, 210],
    path: "M 310,170 L 400,160 L 420,230 L 340,240 L 300,200 Z",
    nodalOfficer: {
      name: "Shri Amitava Bose",
      designation: "District Nodal Officer (Agritech)",
      email: "dno.hazaribagh@jharkhand.gov.in",
      phone: "+91-94311-66299",
      dscVerified: true,
    },
    activeBuilds: 14,
    csrDeployedCr: 0.28,
    civicBacklogCount: 8,
    complaintsLogged: 220,
    complaintsResolved: 198,
    resolutionSpeedHours: 4.5,
    triageMunicipalPercent: 72,
    triageAcademicPercent: 28,
    departments: { water: 6, roads: 4, energy: 2, urban: 2 },
  },
  {
    id: "deoghar",
    name: "Deoghar",
    division: "Santhal Pargana",
    center: [550, 150],
    path: "M 510,120 L 590,120 L 600,180 L 530,190 L 500,150 Z",
    nodalOfficer: {
      name: "Dr. K. S. Pandey",
      designation: "District Nodal Officer (Health & Sensors)",
      email: "dno.deoghar@jharkhand.gov.in",
      phone: "+91-94311-44120",
      dscVerified: true,
    },
    activeBuilds: 11,
    csrDeployedCr: 0.21,
    civicBacklogCount: 7,
    complaintsLogged: 195,
    complaintsResolved: 178,
    resolutionSpeedHours: 4.3,
    triageMunicipalPercent: 68,
    triageAcademicPercent: 32,
    departments: { water: 4, roads: 3, energy: 2, urban: 2 },
  },
  {
    id: "giridih",
    name: "Giridih",
    division: "North Chotanagpur",
    center: [460, 180],
    path: "M 410,140 L 500,130 L 520,200 L 430,210 L 400,170 Z",
    nodalOfficer: {
      name: "Shri Brijesh Sinha",
      designation: "District Nodal Officer",
      email: "dno.giridih@jharkhand.gov.in",
      phone: "+91-94311-99214",
      dscVerified: true,
    },
    activeBuilds: 9,
    csrDeployedCr: 0.18,
    civicBacklogCount: 11,
    complaintsLogged: 210,
    complaintsResolved: 185,
    resolutionSpeedHours: 4.9,
    triageMunicipalPercent: 74,
    triageAcademicPercent: 26,
    departments: { water: 3, roads: 3, energy: 2, urban: 1 },
  },
  {
    id: "ramgarh",
    name: "Ramgarh",
    division: "North Chotanagpur",
    center: [390, 270],
    path: "M 370,250 L 420,245 L 430,285 L 375,290 Z",
    nodalOfficer: {
      name: "Er. Meena Tirkey",
      designation: "District Nodal Officer",
      email: "dno.ramgarh@jharkhand.gov.in",
      phone: "+91-94311-33290",
      dscVerified: true,
    },
    activeBuilds: 7,
    csrDeployedCr: 0.15,
    civicBacklogCount: 5,
    complaintsLogged: 140,
    complaintsResolved: 128,
    resolutionSpeedHours: 3.9,
    triageMunicipalPercent: 60,
    triageAcademicPercent: 40,
    departments: { water: 2, roads: 2, energy: 2, urban: 1 },
  },
  {
    id: "palamu",
    name: "Palamu",
    division: "Palamu",
    center: [180, 160],
    path: "M 130,120 L 220,110 L 235,190 L 160,200 L 120,160 Z",
    nodalOfficer: {
      name: "Dr. Arvind Pathak",
      designation: "District Nodal Officer (Water Resilience)",
      email: "dno.palamu@jharkhand.gov.in",
      phone: "+91-94311-12845",
      dscVerified: true,
    },
    activeBuilds: 8,
    csrDeployedCr: 0.14,
    civicBacklogCount: 15,
    complaintsLogged: 275,
    complaintsResolved: 230,
    resolutionSpeedHours: 5.2,
    triageMunicipalPercent: 75,
    triageAcademicPercent: 25,
    departments: { water: 5, roads: 1, energy: 1, urban: 1 },
  },
  {
    id: "saraikela",
    name: "Saraikela Kharsawan",
    division: "Kolhan",
    center: [480, 410],
    path: "M 440,370 L 520,370 L 530,440 L 460,450 L 430,410 Z",
    nodalOfficer: {
      name: "Shri Deepak Das",
      designation: "District Nodal Officer",
      email: "dno.saraikela@jharkhand.gov.in",
      phone: "+91-94311-89301",
      dscVerified: true,
    },
    activeBuilds: 6,
    csrDeployedCr: 0.11,
    civicBacklogCount: 6,
    complaintsLogged: 160,
    complaintsResolved: 145,
    resolutionSpeedHours: 4.2,
    triageMunicipalPercent: 66,
    triageAcademicPercent: 34,
    departments: { water: 2, roads: 2, energy: 1, urban: 1 },
  },
  {
    id: "west_singhbhum",
    name: "West Singhbhum",
    division: "Kolhan",
    center: [440, 490],
    path: "M 390,440 L 480,440 L 510,540 L 410,550 L 370,490 Z",
    nodalOfficer: {
      name: "Er. Sushil Mundari",
      designation: "District Nodal Officer (Forest & Mining)",
      email: "dno.wsinghbhum@jharkhand.gov.in",
      phone: "+91-94311-76211",
      dscVerified: true,
    },
    activeBuilds: 5,
    csrDeployedCr: 0.09,
    civicBacklogCount: 12,
    complaintsLogged: 215,
    complaintsResolved: 180,
    resolutionSpeedHours: 5.4,
    triageMunicipalPercent: 80,
    triageAcademicPercent: 20,
    departments: { water: 2, roads: 2, energy: 1, urban: 0 },
  },
  {
    id: "dumka",
    name: "Dumka",
    division: "Santhal Pargana",
    center: [610, 190],
    path: "M 570,160 L 660,160 L 670,230 L 590,240 L 560,200 Z",
    nodalOfficer: {
      name: "Shri R. N. Hansda",
      designation: "District Nodal Officer",
      email: "dno.dumka@jharkhand.gov.in",
      phone: "+91-94311-44781",
      dscVerified: true,
    },
    activeBuilds: 6,
    csrDeployedCr: 0.12,
    civicBacklogCount: 8,
    complaintsLogged: 180,
    complaintsResolved: 155,
    resolutionSpeedHours: 4.8,
    triageMunicipalPercent: 71,
    triageAcademicPercent: 29,
    departments: { water: 2, roads: 2, energy: 1, urban: 1 },
  },
  {
    id: "godda",
    name: "Godda",
    division: "Santhal Pargana",
    center: [650, 120],
    path: "M 610,90 L 690,90 L 700,160 L 630,170 L 600,130 Z",
    nodalOfficer: {
      name: "Er. Manoj Jha",
      designation: "District Nodal Officer (Energy Grid)",
      email: "dno.godda@jharkhand.gov.in",
      phone: "+91-94311-66520",
      dscVerified: true,
    },
    activeBuilds: 5,
    csrDeployedCr: 0.16,
    civicBacklogCount: 6,
    complaintsLogged: 165,
    complaintsResolved: 148,
    resolutionSpeedHours: 4.4,
    triageMunicipalPercent: 68,
    triageAcademicPercent: 32,
    departments: { water: 1, roads: 1, energy: 3, urban: 0 },
  },
  {
    id: "sahibganj",
    name: "Sahibganj",
    division: "Santhal Pargana",
    center: [710, 90],
    path: "M 670,60 L 750,60 L 760,130 L 690,140 L 660,100 Z",
    nodalOfficer: {
      name: "Dr. Vikramaditya Sen",
      designation: "District Nodal Officer (River & Water Quality)",
      email: "dno.sahibganj@jharkhand.gov.in",
      phone: "+91-94311-90184",
      dscVerified: true,
    },
    activeBuilds: 4,
    csrDeployedCr: 0.08,
    civicBacklogCount: 22, // High civic distress zone
    complaintsLogged: 290,
    complaintsResolved: 215,
    resolutionSpeedHours: 6.1,
    triageMunicipalPercent: 78,
    triageAcademicPercent: 22,
    departments: { water: 3, roads: 1, energy: 0, urban: 0 },
  },
  {
    id: "pakur",
    name: "Pakur",
    division: "Santhal Pargana",
    center: [710, 160],
    path: "M 680,130 L 750,140 L 760,200 L 690,210 L 670,170 Z",
    nodalOfficer: {
      name: "Shri Sunil Besra",
      designation: "District Nodal Officer",
      email: "dno.pakur@jharkhand.gov.in",
      phone: "+91-94311-22904",
      dscVerified: true,
    },
    activeBuilds: 3,
    csrDeployedCr: 0.05,
    civicBacklogCount: 9,
    complaintsLogged: 140,
    complaintsResolved: 120,
    resolutionSpeedHours: 5.1,
    triageMunicipalPercent: 82,
    triageAcademicPercent: 18,
    departments: { water: 1, roads: 1, energy: 1, urban: 0 },
  },
  {
    id: "jamtara",
    name: "Jamtara",
    division: "Santhal Pargana",
    center: [590, 240],
    path: "M 560,220 L 630,220 L 640,270 L 580,280 L 550,250 Z",
    nodalOfficer: {
      name: "Er. Nitin Gupta",
      designation: "District Nodal Officer (Telecom & Cyber)",
      email: "dno.jamtara@jharkhand.gov.in",
      phone: "+91-94311-38291",
      dscVerified: true,
    },
    activeBuilds: 3,
    csrDeployedCr: 0.04,
    civicBacklogCount: 6,
    complaintsLogged: 130,
    complaintsResolved: 118,
    resolutionSpeedHours: 4.6,
    triageMunicipalPercent: 75,
    triageAcademicPercent: 25,
    departments: { water: 1, roads: 1, energy: 1, urban: 0 },
  },
  {
    id: "chatra",
    name: "Chatra",
    division: "North Chotanagpur",
    center: [270, 160],
    path: "M 230,120 L 310,120 L 320,200 L 250,210 L 220,160 Z",
    nodalOfficer: {
      name: "Shri Dharmendra Kumar",
      designation: "District Nodal Officer",
      email: "dno.chatra@jharkhand.gov.in",
      phone: "+91-94311-54910",
      dscVerified: true,
    },
    activeBuilds: 3,
    csrDeployedCr: 0.05,
    civicBacklogCount: 8,
    complaintsLogged: 155,
    complaintsResolved: 132,
    resolutionSpeedHours: 5.3,
    triageMunicipalPercent: 77,
    triageAcademicPercent: 23,
    departments: { water: 1, roads: 1, energy: 1, urban: 0 },
  },
  {
    id: "koderma",
    name: "Koderma",
    division: "North Chotanagpur",
    center: [370, 120],
    path: "M 330,80 L 410,80 L 420,150 L 350,155 L 320,120 Z",
    nodalOfficer: {
      name: "Dr. Poonam Sethi",
      designation: "District Nodal Officer (Mineral Ecology)",
      email: "dno.koderma@jharkhand.gov.in",
      phone: "+91-94311-81729",
      dscVerified: true,
    },
    activeBuilds: 4,
    csrDeployedCr: 0.06,
    civicBacklogCount: 7,
    complaintsLogged: 145,
    complaintsResolved: 129,
    resolutionSpeedHours: 4.7,
    triageMunicipalPercent: 70,
    triageAcademicPercent: 30,
    departments: { water: 2, roads: 1, energy: 1, urban: 0 },
  },
  {
    id: "latehar",
    name: "Latehar",
    division: "Palamu",
    center: [220, 240],
    path: "M 180,200 L 260,200 L 270,280 L 190,290 L 170,240 Z",
    nodalOfficer: {
      name: "Er. Prabhat Oraon",
      designation: "District Nodal Officer (Watershed Tech)",
      email: "dno.latehar@jharkhand.gov.in",
      phone: "+91-94311-66219",
      dscVerified: true,
    },
    activeBuilds: 3,
    csrDeployedCr: 0.05,
    civicBacklogCount: 16, // Amber alert zone
    complaintsLogged: 210,
    complaintsResolved: 168,
    resolutionSpeedHours: 5.8,
    triageMunicipalPercent: 81,
    triageAcademicPercent: 19,
    departments: { water: 2, roads: 1, energy: 0, urban: 0 },
  },
  {
    id: "garhwa",
    name: "Garhwa",
    division: "Palamu",
    center: [100, 130],
    path: "M 50,80 L 130,80 L 145,170 L 70,180 L 40,130 Z",
    nodalOfficer: {
      name: "Shri Anand Shukla",
      designation: "District Nodal Officer",
      email: "dno.garhwa@jharkhand.gov.in",
      phone: "+91-94311-33118",
      dscVerified: true,
    },
    activeBuilds: 2,
    csrDeployedCr: 0.03,
    civicBacklogCount: 10,
    complaintsLogged: 160,
    complaintsResolved: 135,
    resolutionSpeedHours: 5.5,
    triageMunicipalPercent: 84,
    triageAcademicPercent: 16,
    departments: { water: 1, roads: 1, energy: 0, urban: 0 },
  },
  {
    id: "lohardaga",
    name: "Lohardaga",
    division: "South Chotanagpur",
    center: [280, 310],
    path: "M 250,280 L 320,280 L 330,340 L 260,350 L 240,310 Z",
    nodalOfficer: {
      name: "Er. Kavita Bhagat",
      designation: "District Nodal Officer",
      email: "dno.lohardaga@jharkhand.gov.in",
      phone: "+91-94311-47120",
      dscVerified: true,
    },
    activeBuilds: 3,
    csrDeployedCr: 0.04,
    civicBacklogCount: 5,
    complaintsLogged: 120,
    complaintsResolved: 108,
    resolutionSpeedHours: 4.3,
    triageMunicipalPercent: 73,
    triageAcademicPercent: 27,
    departments: { water: 1, roads: 1, energy: 1, urban: 0 },
  },
  {
    id: "gumla",
    name: "Gumla",
    division: "South Chotanagpur",
    center: [250, 390],
    path: "M 200,340 L 290,340 L 300,430 L 220,440 L 190,390 Z",
    nodalOfficer: {
      name: "Shri Lucas Beck",
      designation: "District Nodal Officer (Agritech & Cold Chain)",
      email: "dno.gumla@jharkhand.gov.in",
      phone: "+91-94311-92813",
      dscVerified: true,
    },
    activeBuilds: 3,
    csrDeployedCr: 0.04,
    civicBacklogCount: 6,
    complaintsLogged: 135,
    complaintsResolved: 121,
    resolutionSpeedHours: 4.8,
    triageMunicipalPercent: 78,
    triageAcademicPercent: 22,
    departments: { water: 1, roads: 1, energy: 1, urban: 0 },
  },
  {
    id: "simdega",
    name: "Simdega",
    division: "South Chotanagpur",
    center: [250, 480],
    path: "M 210,440 L 290,440 L 300,530 L 220,540 L 190,490 Z",
    nodalOfficer: {
      name: "Smt. Clara Kujur",
      designation: "District Nodal Officer",
      email: "dno.simdega@jharkhand.gov.in",
      phone: "+91-94311-73918",
      dscVerified: true,
    },
    activeBuilds: 2,
    csrDeployedCr: 0.03,
    civicBacklogCount: 5,
    complaintsLogged: 110,
    complaintsResolved: 99,
    resolutionSpeedHours: 4.9,
    triageMunicipalPercent: 82,
    triageAcademicPercent: 18,
    departments: { water: 1, roads: 1, energy: 0, urban: 0 },
  },
  {
    id: "khunti",
    name: "Khunti",
    division: "South Chotanagpur",
    center: [360, 380],
    path: "M 320,350 L 400,350 L 410,410 L 340,420 L 310,380 Z",
    nodalOfficer: {
      name: "Er. Birsa Munda",
      designation: "District Nodal Officer (Tribal Bio-Resources)",
      email: "dno.khunti@jharkhand.gov.in",
      phone: "+91-94311-19283",
      dscVerified: true,
    },
    activeBuilds: 4,
    csrDeployedCr: 0.06,
    civicBacklogCount: 4,
    complaintsLogged: 115,
    complaintsResolved: 106,
    resolutionSpeedHours: 4.1,
    triageMunicipalPercent: 67,
    triageAcademicPercent: 33,
    departments: { water: 1, roads: 1, energy: 1, urban: 1 },
  },
];

export const GIS_PINS: GisMapPin[] = [
  // Academic Hubs (Graduation Cap)
  {
    id: "pin-acad-bit-mesra",
    type: "academic",
    title: "BIT Mesra Academic Lab Hub",
    subtitle: "Department of Chemical & Electrical Engineering",
    district: "Ranchi",
    x: 375,
    y: 295,
    department: "Energy",
    details: {
      activeTeams: 18,
      labFacilities: ["Smart Grid Simulator Lab", "Micro-Turbine Testing Rig", "Polymer Membrane Lab"],
      deployedPoCs: ["Mine Leachate Filtration Cart", "Solar Micro-Inverter 5kVA", "Cold-Storage Controller"],
    },
  },
  {
    id: "pin-acad-nit-jsr",
    type: "academic",
    title: "NIT Jamshedpur Innovation Lab",
    subtitle: "Department of Metallurgy & Materials Science",
    district: "East Singhbhum",
    x: 555,
    y: 420,
    department: "Roads",
    details: {
      activeTeams: 14,
      labFacilities: ["Slag Asphalt Synthesis Cell", "Corrosion Stress Chamber", "High-Torque EV Dyno"],
      deployedPoCs: ["LD-Slag Road Binder Gen-3", "Automated Pothole Profiler", "Battery Thermal Enclosure"],
    },
  },
  {
    id: "pin-acad-iit-ism",
    type: "academic",
    title: "IIT (ISM) Dhanbad Clean Mining Hub",
    subtitle: "Centre of Excellence in Mine Water & Safety",
    district: "Dhanbad",
    x: 515,
    y: 230,
    department: "Water",
    details: {
      activeTeams: 16,
      labFacilities: ["Acid Mine Drainage Pilot", "Sub-surface Methane Detection Cell", "Centrifugal Slurry Loop"],
      deployedPoCs: ["Selective Arsenic & Iron Filter", "Acoustic Gas Detector", "Tailings Pozzolan Mortar"],
    },
  },

  // Corporate Sponsors (Industrial Building)
  {
    id: "pin-corp-tata-steel",
    type: "corporate",
    title: "Tata Steel CSR R&D Testing Center",
    subtitle: "Industrial Ecology & Circular Economy Division",
    district: "East Singhbhum",
    x: 575,
    y: 440,
    department: "Roads",
    details: {
      pledgedCapitalCr: 1.85,
      activeMentors: 8,
      testingFacilitiesOpened: ["Heavy Vehicle Test Track", "Slag Durability Yard", "Industrial Effluent Sampling Desk"],
    },
  },
  {
    id: "pin-corp-bccl",
    type: "corporate",
    title: "BCCL / Coal India CSR Innovation Desk",
    subtitle: "Environmental Management & Community Water Wing",
    district: "Dhanbad",
    x: 535,
    y: 250,
    department: "Water",
    details: {
      pledgedCapitalCr: 1.45,
      activeMentors: 6,
      testingFacilitiesOpened: ["Jharia Pit Water Treatment Station", "Dust Suppression Trial Corridor", "Overburden Revegetation Sector"],
    },
  },
  {
    id: "pin-corp-adani-power",
    type: "corporate",
    title: "Adani Thermal Power Green CSR Cell",
    subtitle: "Ultra-Supercritical Ash Utilization Wing",
    district: "Godda",
    x: 645,
    y: 110,
    department: "Energy",
    details: {
      pledgedCapitalCr: 0.9,
      activeMentors: 4,
      testingFacilitiesOpened: ["Fly Ash Geopolymer Brick Yard", "Micro-Irrigation Solar Pump Grid"],
    },
  },

  // Active Bench Trials (Flask)
  {
    id: "pin-trial-mine-water",
    type: "bench_trial",
    title: "Mine Water Desalination & Chelation Rig",
    subtitle: "TRL-5 Prototype Validation on Pit Discharge",
    district: "Dhanbad",
    x: 505,
    y: 255,
    department: "Water",
    details: {
      trlLevel: 5,
      benchParameters: "Flow rate: 12,000 L/hr, Turbidity drop: 99.4%, Heavy metal reduction: 98.2%",
    },
  },
  {
    id: "pin-trial-slag-asphalt",
    type: "bench_trial",
    title: "LD Slag High-Toughness Bitumen Blend",
    subtitle: "TRL-6 Municipal Highway Stress Trial",
    district: "East Singhbhum",
    x: 540,
    y: 410,
    department: "Roads",
    details: {
      trlLevel: 6,
      benchParameters: "Marshall stability: 18.5 kN, Rutting depth: <1.8mm at 60°C, 40% cost saving vs standard mix",
    },
  },
  {
    id: "pin-trial-smart-grid",
    type: "bench_trial",
    title: "IoT Feeder Microgrid Autonomous Recloser",
    subtitle: "TRL-4 Low-Voltage Line Fault Isolation",
    district: "Ranchi",
    x: 395,
    y: 320,
    department: "Energy",
    details: {
      trlLevel: 4,
      benchParameters: "Trip latency: 18ms, Fault isolation precision: 99.8%, Cellular LoRaWAN failover verified",
    },
  },

  // Amber Alert Distress Zones (One-Click Seed Grant)
  {
    id: "pin-amber-sahibganj-arsenic",
    type: "amber_alert",
    title: "Critical Arsenic & Fluoride Influx",
    subtitle: "Rajmahal Alluvial Aquifer Contamination",
    district: "Sahibganj",
    x: 705,
    y: 85,
    department: "Water",
    details: {
      urgency: "Critical",
      verifiedByDno: "Dr. Vikramaditya Sen (DNO Sahibganj)",
      seedGrantEligible: true,
      seedGrantAmountCr: 0.25, // ₹25 Lakhs
      problemDescription: "Over 14,000 villagers across 8 wards exposed to arsenic levels exceeding 0.08 mg/L (8x WHO limit). 3 routine water filters failed due to iron co-precipitation. Immediate deep-tech bio-sorption or hollow-fiber filtration trial required.",
    },
  },
  {
    id: "pin-amber-latehar-siltation",
    type: "amber_alert",
    title: "North Koel Catchment Severe Siltation",
    subtitle: "Bauxite Runoff Blocking Canal Gate Intakes",
    district: "Latehar",
    x: 215,
    y: 235,
    department: "Water",
    details: {
      urgency: "High",
      verifiedByDno: "Er. Prabhat Oraon (DNO Latehar)",
      seedGrantEligible: true,
      seedGrantAmountCr: 0.25, // ₹25 Lakhs
      problemDescription: "Monsoon sediment from upstream unpaved bauxite hauling roads has clogged canal lift pumps for 4 agricultural panchayats. Requires low-cost acoustic acoustic desiltation or automated sediment-trap barrier prototype.",
    },
  },
];

export const INITIAL_IP_QUEUE: IpQueueItem[] = [
  {
    id: "IP-2026-001",
    projectName: "Mine Water Purification & Heavy Metal Chelation System",
    hostUniversity: "IIT (ISM) Dhanbad",
    corporatePartner: "Bharat Coking Coal Limited (BCCL)",
    status: "Bilateral DSC Verified",
    compliant: true,
    submittedDate: "2026-09-02",
    trl: 6,
    hash: "3a7f8e12b04c559df48a91c258d4a67923fae1208945de21b44910cf91a34b22",
    department: "Water",
    certificateId: "JH-GOV-IP-2026-8841",
  },
  {
    id: "IP-2026-002",
    projectName: "Autonomous Feeder Microgrid Fault-Isolator & Recloser",
    hostUniversity: "BIT Mesra, Ranchi",
    corporatePartner: "JBVNL / Tata Power Consortium",
    status: "Bilateral DSC Verified",
    compliant: true,
    submittedDate: "2026-09-04",
    trl: 5,
    hash: "91b8a34cd05177ef8821094ab23f990145cbe234019a82bbef34591ca0187c33",
    department: "Energy",
    certificateId: "JH-GOV-IP-2026-8842",
  },
  {
    id: "IP-2026-003",
    projectName: "LD Steel Slag High-Performance Bitumen Road Binder",
    hostUniversity: "NIT Jamshedpur",
    corporatePartner: "Tata Steel Industrial Infrastructure",
    status: "Bilateral DSC Verified",
    compliant: true,
    submittedDate: "2026-09-05",
    trl: 7,
    hash: "fa829014bc0891d44ef1092ab5641980ca123df78190be90876123498afe2154",
    department: "Roads",
    certificateId: "JH-GOV-IP-2026-8843",
  },
  {
    id: "IP-2026-004",
    projectName: "IoT Turbidity & Contaminant Acoustic Flow Meter",
    hostUniversity: "Birsa Institute of Technology, Sindri",
    corporatePartner: "Jamshedpur Utilities & Water Co (JUWS)",
    status: "Pending",
    compliant: false,
    submittedDate: "2026-09-07",
    trl: 4,
    hash: "7721093fbd0941acb981290fe345091ca9012356bcde4390128475fed12398ab",
    department: "Water",
  },
  {
    id: "IP-2026-005",
    projectName: "Solar Cold-Storage Phase-Change Refrigeration Module",
    hostUniversity: "Ranchi University (Dept of Physics)",
    corporatePartner: "Jharkhand State Agro-Industries Corp",
    status: "Pending",
    compliant: false,
    submittedDate: "2026-09-08",
    trl: 4,
    hash: "1894a02beff38471920acb09182390fade891230491827364501928374650192",
    department: "Urban",
  },
];

export const MASTER_PROJECTS_DATA: CivicProject[] = [
  {
    id: "PRJ-JH-01",
    title: "Mine Water Desalination & Arsenic Chelation Plant",
    summary: "Hollow-fiber polymer membrane system treating 100,000 L/day acid mine drainage into BIS-10500 potable water.",
    district: "Dhanbad",
    department: "Water",
    university: "IIT (ISM) Dhanbad",
    leadPi: "Prof. S. K. Bhattacharya",
    corporateSponsor: "Bharat Coking Coal Limited (BCCL)",
    trl: 6,
    trlStage: "TRL 6: Prototype System Tested in Field Environment",
    escrowFundingCr: 0.65,
    status: "Field Testing",
    lastAuditDate: "2026-08-28",
  },
  {
    id: "PRJ-JH-02",
    title: "Steel Slag Composite for Heavy-Duty High-Rainfall Roadways",
    summary: "Replacing 45% natural stone aggregate with chemically neutralized LD slag to resist heavy mining truck wheel rutting.",
    district: "East Singhbhum",
    department: "Roads",
    university: "NIT Jamshedpur",
    leadPi: "Dr. Meenakshi Sundaram",
    corporateSponsor: "Tata Steel Limited",
    trl: 7,
    trlStage: "TRL 7: Full-Scale Operational Demonstration",
    escrowFundingCr: 0.85,
    status: "Municipal Trial",
    lastAuditDate: "2026-09-01",
  },
  {
    id: "PRJ-JH-03",
    title: "Solar-Powered LoRaWAN Substation Fault Predictor",
    summary: "Predictive vibration and thermal acoustic node deployed on rural 11kV distribution feeders to stop forest wildfire sparking.",
    district: "Ranchi",
    department: "Energy",
    university: "BIT Mesra",
    leadPi: "Dr. Avinash Roy",
    corporateSponsor: "Tata Power Renewable Energy",
    trl: 5,
    trlStage: "TRL 5: Component Tested in Relevant Environment",
    escrowFundingCr: 0.45,
    status: "Bench Prototyping",
    lastAuditDate: "2026-08-15",
  },
  {
    id: "PRJ-JH-04",
    title: "AI-Driven Automated Urban Waste Sorter & Pyrolysis Kiln",
    summary: "Robotic multi-spectral optical sorter separating municipal polyolefins for continuous conversion to low-sulfur diesel oil.",
    district: "Ranchi",
    department: "Urban",
    university: "Ranchi University",
    leadPi: "Er. Rameshwar Oraon",
    corporateSponsor: "Adani Environment Solutions",
    trl: 4,
    trlStage: "TRL 4: Laboratory Rig Verification",
    escrowFundingCr: 0.35,
    status: "Bench Prototyping",
    lastAuditDate: "2026-08-20",
  },
  {
    id: "PRJ-JH-05",
    title: "Underground Coal Fire Thermal Acoustic Early-Warning Network",
    summary: "Sealed fiber-optic distributed acoustic sensing (DAS) cables buried 15m deep across Jharia coal township seam boundary.",
    district: "Dhanbad",
    department: "Energy",
    university: "IIT (ISM) Dhanbad",
    leadPi: "Dr. Tapas Kumar Mandal",
    corporateSponsor: "Coal India Limited",
    trl: 8,
    trlStage: "TRL 8: System Qualified Through Municipal Operational Test",
    escrowFundingCr: 0.92,
    status: "Certified Commercial",
    lastAuditDate: "2026-09-03",
  },
  {
    id: "PRJ-JH-06",
    title: "Arsenic Nano-Filter Cartridge for Rural Handpumps",
    summary: "Low-cost graphene oxide iron hydroxide adsorbent canister attaching directly to standard India Mark II handpumps.",
    district: "Sahibganj",
    department: "Water",
    university: "BIT Sindri",
    leadPi: "Dr. Sanjoy Murmu",
    corporateSponsor: "Adani Foundation CSR",
    trl: 5,
    trlStage: "TRL 5: Field Tested on Contaminated Tubewells",
    escrowFundingCr: 0.28,
    status: "Field Testing",
    lastAuditDate: "2026-08-30",
  },
  {
    id: "PRJ-JH-07",
    title: "Bio-Enzymatic Dust Suppressant for Iron Ore Haul Roads",
    summary: "Organic sugarcane molasses and bacterial cellulose spray preventing particulate dust suspension for up to 96 hours per application.",
    district: "West Singhbhum",
    department: "Roads",
    university: "NIT Jamshedpur",
    leadPi: "Dr. Shalini Prasad",
    corporateSponsor: "Tata Steel Mining Division",
    trl: 6,
    trlStage: "TRL 6: Prototype Tested on Heavy Haul Corridors",
    escrowFundingCr: 0.4,
    status: "Municipal Trial",
    lastAuditDate: "2026-08-25",
  },
  {
    id: "PRJ-JH-08",
    title: "Micro-Hydro Pelton Wheel Generator for Hill Tribe Hamlets",
    summary: "3kW modular composite turbine operating on natural perennial waterfall drops to electrify off-grid primitive tribal groups (PVTGs).",
    district: "Gumla",
    department: "Energy",
    university: "BIT Mesra",
    leadPi: "Prof. Hemant K. Sahu",
    corporateSponsor: "Usha Martin Foundation",
    trl: 7,
    trlStage: "TRL 7: Operational Demonstration in 3 Hamlets",
    escrowFundingCr: 0.22,
    status: "Municipal Trial",
    lastAuditDate: "2026-08-10",
  },
  {
    id: "PRJ-JH-09",
    title: "Fly Ash Ceramic Permeable Pavement for Urban Flood Mitigation",
    summary: "Ultra-porous interlocking paver blocks absorbing 400mm/hr cloudburst water directly into subsoil groundwater recharge aquifers.",
    district: "Bokaro",
    department: "Urban",
    university: "BIT Sindri",
    leadPi: "Dr. B. K. Soren",
    corporateSponsor: "Bokaro Steel Plant (SAIL)",
    trl: 5,
    trlStage: "TRL 5: Laboratory Hydraulic Stress Validated",
    escrowFundingCr: 0.3,
    status: "Bench Prototyping",
    lastAuditDate: "2026-08-19",
  },
  {
    id: "PRJ-JH-10",
    title: "Solar Lift Irrigation Drone Telemetry & Soil Moisture Valve",
    summary: "Autonomous solar pump array with sub-surface capacitive soil moisture probes dispatching water via zigbee mesh network.",
    district: "Palamu",
    department: "Water",
    university: "Birsa Agricultural University",
    leadPi: "Dr. N. P. Mahto",
    corporateSponsor: "L&T Public Charitable Trust",
    trl: 6,
    trlStage: "TRL 6: Field Verified Across 40 Hectares",
    escrowFundingCr: 0.48,
    status: "Field Testing",
    lastAuditDate: "2026-09-02",
  },
  {
    id: "PRJ-JH-11",
    title: "Natural Lac Biomaterial Coating for Eco-Friendly Food Packaging",
    summary: "Food-grade waterproof and antimicrobial barrier derived from Palas tree resin, completely replacing single-use LDPE wraps.",
    district: "Khunti",
    department: "Urban",
    university: "ICAR Indian Institute of Natural Resins & Gums",
    leadPi: "Dr. R. K. Yogesh",
    corporateSponsor: "Jusco / Tata Consumables",
    trl: 7,
    trlStage: "TRL 7: Commercial Production Line Verified",
    escrowFundingCr: 0.38,
    status: "Municipal Trial",
    lastAuditDate: "2026-08-22",
  },
  {
    id: "PRJ-JH-12",
    title: "Smart Waste Water Micro-Algae Bioreactor for Heavy Metals",
    summary: "Spirulina and chlorella photo-bioreactor stripping nickel, chromium, and cadmium from electroplating industrial cluster effluents.",
    district: "Saraikela",
    department: "Water",
    university: "NIT Jamshedpur",
    leadPi: "Dr. Geeta Kumari",
    corporateSponsor: "Adityapur Industrial Area Development Authority",
    trl: 4,
    trlStage: "TRL 4: Rig Validated in Laboratory",
    escrowFundingCr: 0.25,
    status: "Bench Prototyping",
    lastAuditDate: "2026-08-14",
  },
];

export const IP_REGISTRY_LEDGER: IpRegistryItem[] = [
  {
    id: "REG-2026-0881",
    title: "Mine Water Acid Neutralization & Iron Precipitation Reactor",
    hostUniversity: "IIT (ISM) Dhanbad",
    ttoSignatory: "Prof. V. M. S. R. Murthy (Dean R&D)",
    corporateSponsor: "Bharat Coking Coal Limited",
    corporateLegalOfficer: "Adv. S. K. Mukherjee (Chief Legal Advisor)",
    negotiatedSplit: "50% University / 50% Industry",
    uniSharePercent: 50,
    corpSharePercent: 50,
    hash: "a4f89012bc0914872910ab34091cdef87129038475fedcba0192837465019283",
    status: "Active License",
    licenseType: "Exclusive Municipal Field License",
    royaltiesDistributedCr: 0.45,
    registrationDate: "2026-03-14",
    patentNumber: "IN-2026-JH-10492",
  },
  {
    id: "REG-2026-0882",
    title: "LD Slag High-Durability Geopolymer Aggregate Formulation",
    hostUniversity: "NIT Jamshedpur",
    ttoSignatory: "Dr. M. K. Paswan (TTO In-Charge)",
    corporateSponsor: "Tata Steel Infrastructure Division",
    corporateLegalOfficer: "Adv. Rohit Bajaj (Head Corporate Legal)",
    negotiatedSplit: "60% University / 40% Industry",
    uniSharePercent: 60,
    corpSharePercent: 40,
    hash: "3b890145ca0918239401ab982309fcde1209384756abcdef0918273645019284",
    status: "Registered & Locked",
    licenseType: "Commercial Co-Ownership License",
    royaltiesDistributedCr: 0.55,
    registrationDate: "2026-04-20",
    patentNumber: "IN-2026-JH-10518",
  },
  {
    id: "REG-2026-0883",
    title: "Substation Thermal LoRaWAN Predictive Telemetry Firmware",
    hostUniversity: "BIT Mesra, Ranchi",
    ttoSignatory: "Prof. P. R. Thakura (Dean IP & Tech Transfer)",
    corporateSponsor: "Tata Power Renewable Energy",
    corporateLegalOfficer: "Adv. Ananya Sengupta (VP Legal)",
    negotiatedSplit: "50% University / 50% Industry",
    uniSharePercent: 50,
    corpSharePercent: 50,
    hash: "9102837465ab0918273645fcde1209384756a1b2c3d4e5f60718293041526374",
    status: "Commercialized",
    licenseType: "Perpetual Technology Transfer",
    royaltiesDistributedCr: 0.38,
    registrationDate: "2026-05-11",
    patentNumber: "IN-2026-JH-10554",
  },
  {
    id: "REG-2026-0884",
    title: "Underground Mine Methane Acoustic Warning Sensor",
    hostUniversity: "IIT (ISM) Dhanbad",
    ttoSignatory: "Prof. V. M. S. R. Murthy (Dean R&D)",
    corporateSponsor: "Coal India Limited (HQ)",
    corporateLegalOfficer: "Adv. G. C. Mohanty (Executive Director Law)",
    negotiatedSplit: "40% University / 60% Industry",
    uniSharePercent: 40,
    corpSharePercent: 60,
    hash: "781290384756ca0918239401ab982309fcde1209384756abcdef091827364501",
    status: "Royalty Distributed",
    licenseType: "Non-Exclusive Public Safety License",
    royaltiesDistributedCr: 0.42,
    registrationDate: "2026-06-18",
    patentNumber: "IN-2026-JH-10599",
  },
];

export const REPORT_TEMPLATES: ReportConfig[] = [
  {
    id: "rep-cm-brief",
    title: "Chief Minister's Office Executive Innovation Brief",
    recipient: "Chief Minister's Secretariat, Project Monitoring Unit",
    frequency: "Quarterly Statutory Compliance",
    description: "Executive high-level summary of all 186 active civic builds, district grievance triage velocity, and CSR escrow capital disbursements across Jharkhand.",
    metricsCovered: [
      "Total Active R&D Projects (186)",
      "CSR Fund Milestone Releases (₹4.2 Cr)",
      "Patents & DigiLocker Certificates Issued (38)",
      "High Backlog Distress Zones Resolved (14)",
    ],
    lastGenerated: "2026-09-01 10:30 AM",
  },
  {
    id: "rep-higher-ed",
    title: "Higher & Technical Education Department R&D Yield Audit",
    recipient: "Secretary, Dept of Higher & Technical Education, Govt of Jharkhand",
    frequency: "Monthly Institutional Performance",
    description: "Granular university-by-university audit tracking lab capacity, faculty PI disclosures, student researcher stipends, and TRL 1 to 9 graduation rates.",
    metricsCovered: [
      "University Lab Utilization (BIT, NIT, IIT ISM, BIT Sindri)",
      "NISP Policy Bilateral Compliance Rate (100%)",
      "Student DigiLocker Innovation Credentials",
      "Faculty Patent Royalty Distributions (₹1.8 Cr)",
    ],
    lastGenerated: "2026-09-05 04:15 PM",
  },
  {
    id: "rep-niti-aayog",
    title: "NITI Aayog & DST Central Innovation & CSR Section 135 Ledger",
    recipient: "NITI Aayog (Atal Innovation Mission) & Department of Science & Technology",
    frequency: "Bi-Annual National Reporting",
    description: "Standardized national compliance filing documenting corporate CSR fund movement into verified state academic engineering labs for societal impact.",
    metricsCovered: [
      "CSR Schedule VII Alignment",
      "Tripartite Legal Agreement Hashes",
      "Municipal Field Validation Reports",
      "State-Funded Seed Grants Allocated",
    ],
    lastGenerated: "2026-08-31 02:00 PM",
  },
  {
    id: "rep-dno-triage",
    title: "Statewide 24-District DNO Grievance Triage & Resolution Ledger",
    recipient: "Principal Secretary, Urban Development & Panchayati Raj Dept",
    frequency: "Weekly Administrative Telemetry",
    description: "Operational scoreboard for all 24 District Nodal Officers measuring complaint turnaround time, municipal work orders issued, and deep-tech escalation ratios.",
    metricsCovered: [
      "Complaints Logged (4,820 statewide)",
      "Average Resolution Speed (4.2 Hours)",
      "Municipal vs Academia Escalation Split (71% / 29%)",
      "Active Distress Zones Triggering State Seed Grants",
    ],
    lastGenerated: "2026-09-08 09:00 AM",
  },
];
